export enum SubmissionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  VIEWER = 'VIEWER',
}

export enum AuditAction {
  SUBMISSION_CREATED = 'SUBMISSION_CREATED',
  SUBMISSION_APPROVED = 'SUBMISSION_APPROVED',
  SUBMISSION_REJECTED = 'SUBMISSION_REJECTED',
  SUBMISSION_POINTS_ASSIGNED = 'SUBMISSION_POINTS_ASSIGNED',
  REFERRER_CREATED = 'REFERRER_CREATED',
  REFERRER_UPDATED = 'REFERRER_UPDATED',
  REFERRER_DEACTIVATED = 'REFERRER_DEACTIVATED',
  ADMIN_CREATED = 'ADMIN_CREATED',
  ADMIN_UPDATED = 'ADMIN_UPDATED',
  ADMIN_DELETED = 'ADMIN_DELETED',
  SCORE_RULE_CREATED = 'SCORE_RULE_CREATED',
  SCORE_RULE_UPDATED = 'SCORE_RULE_UPDATED',
  SCORE_RULE_DELETED = 'SCORE_RULE_DELETED',
  BOT_MESSAGE_UPDATED = 'BOT_MESSAGE_UPDATED',
  SYSTEM_SETTING_UPDATED = 'SYSTEM_SETTING_UPDATED',
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  ADMIN_LOGOUT = 'ADMIN_LOGOUT',
}

export enum SubmissionEventType {
  CREATED = 'CREATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  POINTS_ASSIGNED = 'POINTS_ASSIGNED',
  NOTE_ADDED = 'NOTE_ADDED',
  REVIEWED = 'REVIEWED',
}

export enum SettingType {
  STRING = 'string',
  NUMBER = 'number',
  BOOLEAN = 'boolean',
  JSON = 'json',
}

export enum QueueName {
  TELEGRAM_NOTIFICATIONS = 'telegram-notifications',
  LEADERBOARD_RECALC = 'leaderboard-recalc',
  ADMIN_TASKS = 'admin-tasks',
}

export enum JobName {
  SEND_APPROVAL_NOTIFICATION = 'send-approval-notification',
  SEND_REJECTION_NOTIFICATION = 'send-rejection-notification',
  RECALC_LEADERBOARD = 'recalc-leaderboard',
  EXPORT_LEADERBOARD = 'export-leaderboard',
}
